#!/bin/bash

if [[ $(docker ps -a --filter "name=reactapp" --format "{{.Names}}" | wc -l) > 0 ]];then
  if [[ $(docker ps --filter "name=reactapp" --format "{{.Names}}" | wc -l) == 0 ]];then  
    docker start reactapp   
  fi  
else  
  if [[ $(docker images --format "{{.Repository}}" | grep "reactapp-img" | wc -l) == 0 ]];then
    docker build -t shridharalve/node:reactapp-img -f "$(git rev-parse --show-toplevel)"/automation/Dockerfile
  fi
  docker run -d -v /var/www/emoji-search:/var/www/emoji-search --name reactapp shridharalve/node:reactapp-img  
fi

docker exec -d reactapp bash -c "cd /var/www/emoji-search/ && npm install --unsafe && npm run build"